# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Second language: Chinese
zh:
  languageCode: zh-Hans
  languageName: 简体中文
  contentDir: content/zh
  title: 毛威的学术主页
  params:
    description: 佛罗里达州立大学水文学研究者毛威的学术网站
  weight: 2
